spring:
  application:
    name: sim-tim-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/simtim}
    username: ${DB_USER:simtim}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
